-- 003_oauth_and_vacancy_filters.sql
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(50) DEFAULT 'local';
ALTER TABLE users ADD COLUMN IF NOT EXISTS external_id VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pinfl VARCHAR(14);
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;

ALTER TABLE vacancies ADD COLUMN IF NOT EXISTS category VARCHAR(100) DEFAULT 'IT & Dasturlash';
ALTER TABLE vacancies ADD COLUMN IF NOT EXISTS job_type VARCHAR(50) DEFAULT 'Full-time';
ALTER TABLE vacancies ADD COLUMN IF NOT EXISTS experience VARCHAR(50) DEFAULT '1-3 yil';
ALTER TABLE vacancies ADD COLUMN IF NOT EXISTS tags VARCHAR(255) DEFAULT '';
ALTER TABLE vacancies ADD COLUMN IF NOT EXISTS company_logo TEXT DEFAULT '';
ALTER TABLE vacancies ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT true;
